### ISSUE TITLE
Pre answer the questions?

### ISSUE THREAD

**Issue by simpleapps-io** [ramsey/php-library-skeleton#33]
How do I use the answer file or otherwise give the starter kit the answers before running the command?

**Comment by ramsey** [comment]
The answer file is provided as a convenience, in case the user quits the wizard before finishing the questions.

I hadn't considered a use case where users might want to pre-answer the questions, but that's something that might be possible. The answers file is named `.starter-kit-answers` and is located in the root of the project. The data consists of all the public properties of `Ramsey\Dev\LibraryStarterKit\Answers` encoded as a JSON object. It might be possible to pass an additional parameter to the `composer create-project` command that tells it the location of an existing answers file to load.

Can you tell me more about this use case, so I can get a better understanding of how you want to use it?

**Comment by simpleapps-io** [comment]
Here is the use case. I'm creating a series of microservices based on https://github.com/spiral/framework Each service is going to have a library that has code that is auto-generated for the client library/SDK, the libraries are based on this starter kit and then the generated code is placed into the library and customized with https://github.com/nikic/PHP-Parser

The lead microservice in the project already has the code to pull in details from SQLServer about the columns, create the microservice app, generate the gRPC/Protobuf files, and created the client library with tests and data validation.

I'm looking to replicate this process and set up at least 10 more times for other microservices, possibly 25+ times. If I could pre-generate the answers for the library (outside of the project folder) I would be able to take out a large manual step. If the format documentation and a command-line option for pointing to an answer file were available that would be wonderful. 

I think the file would need to live outside the project folder as I got an error message about the folder not being empty when I tried to create an answer file in the location it appeared to expect it. This would fit well into my design as I have folders for each microservice that have details about how it is set up and options for the code builder to create the code.

I can provide more details on the system in a direct message if needed.

**Comment by ramsey** [comment]
Sounds good. I think this is enough information. I need to figure out how to pass additional parameters when using `composer create-project`, but once I've figured that out, the rest of it should be pretty straightforward.

**Comment by simpleapps-io** [comment]
Excellent

**Comment by simpleapps-io** [comment]
Would it be easier to look for environment variables? or maybe an environment variable that points to the answers file?

**Comment by ramsey** [comment]
@simpleapps-io An environment variable is definitely easier and is a great idea. Thanks!

Check out the notes here on the 3.3.0 tag, and give it a try: https://github.com/ramsey/php-library-starter-kit/releases/tag/3.3.0

**Comment by ramsey** [comment]
@simpleapps-io, was this useful for your needs?

**Comment by simpleapps-io** [comment]
I missed the update. I will test within the new few days. Thank you.

**Comment by simpleapps-io** [comment]
I ended up writing a Symfony command to create the answer file and once I get the format and parameters correct it works great! Thank you!

**Comment by ramsey** [comment]
Awesome! That's great to hear. Thanks for the feature idea.
