### ISSUE TITLE
Error after fresh install at running composer dev:* script

### ISSUE THREAD

**Issue by Zerogiven** [ramsey/php-library-skeleton#40]
I made a fresh "create-project" but i can't get it running and have no idea why..

```bash
composer dev:analyze:all

Executing dev:analyze:phpstan

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\Process::isTtySupported() in /var/www/html/vendor/ramsey/devtools-lib/src/Composer/Command/ProcessCommand.php:68
Stack trace:
#0 /var/www/html/vendor/ramsey/devtools-lib/src/Composer/Command/BaseCommand.php(94): Ramsey\Dev\Tools\Composer\Command\ProcessCommand->doExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Ramsey\Dev\Tools\Composer\Command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/ramsey/devtools-lib/src/Composer/Command/AnalyzeCommand.php(65): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/ramsey/devtools-lib/src/Composer/Command/BaseCommand.php(94): Ramsey\Dev in /var/www/html/vendor/ramsey/devtools-lib/src/Composer/Command/ProcessCommand.php on line 68
```

What i don't get is that the symfony process package is installed and of course the static function is available at the process class. I tried making a composer dump-autoload but this changed nothing.

Maybe you have an idea cause i think it's not a (my) client problem cause the github workflows are failing too...

However, cheers and thanks for the lib, it saved me a lot of time using it at one of my libs :)

**Comment by ramsey** [comment]
Hi, @Zerogiven !

I'm sorry you're encountering this. This is because the version of symfony/process that the plugin uses is actually the version bundled with Composer and not the version installed in the `vendor/` directory.

See here for more details: https://github.com/ramsey/devtools-lib/issues/90

I'm working on a solution that will fix this.

**Comment by Zerogiven** [comment]
Thanks, glad to hear :)

and sry - i forgot to look at the issues inside the devtools-lib repo for an existing ticket, only looked at this repo, so i close the ticket :)
